@YanakApp_HostAddress = https://localhost:7096


GET {{YanakApp_HostAddress}}/api/users

###

POST {{YanakApp_HostAddress}}/api/users
Content-Type: application/json

{
  "FirstName":"Gosho",
  "LastName":"Goshev",
  "email":"goshogoshev@gmail.com",
  "password":"12345"

}

###

@id=15
DELETE {{YanakApp_HostAddress}}/api/users/{{id}}

###

GET {{YanakApp_HostAddress}}/api/users/{{id}}

###

PUT {{YanakApp_HostAddress}}/api/users/{{id}}
Content-Type: application/json

{
  "Id":2,
  "FirstName":"Gosho",
  "LastName":"Goshev",
  "email":"goshogoshev@gmail.com",
  "password":"12345"
}

###

GET {{YanakApp_HostAddress}}/api/products

###

POST {{YanakApp_HostAddress}}/api/products
Content-Type: application/json

{
  "Name":"Loki Toki",
  "Description":"talking to others"

}

###

DELETE {{YanakApp_HostAddress}}/api/products/{{id}}

###

GET {{YanakApp_HostAddress}}/api/products/{{id}}

###

PUT {{YanakApp_HostAddress}}/api/products/{{id}}
Content-Type: application/json

{
  //Product
}

###

GET {{YanakApp_HostAddress}}/api/products/{{id}}

###

@userId=2
@productId=17
PUT {{YanakApp_HostAddress}}/api/users/{{userId}}/products/{{productId}}

###

PUT {{YanakApp_HostAddress}}/api/users/{{id}}
Content-Type: application/json

{
  //UpdateUserDto
}

###
